import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import Navbar from '../app/(components)/navbar'
import Footer from '../app/(components)/footer'

import './globals.css' 

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />    
        {children}
        <Footer />  
      </body>  
    </html>
  );
}
